name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Checkout code
    
    - name: Builds the C# code       
      run: dotnet build              
       
    - name: Runs the C# tests       
      run: dotnet test              
       
    - name: Builds the typescript code.     
      working-directory: ./DotnetTemplate.Web
      run: | 
        npm install              
        npm run build
     
    - name: Runs the linter on the typescript code.       
      working-directory: ./DotnetTemplate.Web
      run: npm run lint             
      
    - name: Runs the typescript tests       
      working-directory: ./DotnetTemplate.Web
      run: npm t                           
      
    
    
    
    
    #Builds the C# code.
    #Runs the C# tests.
    #Builds the typescript code.
    #Runs the linter on the typescript code.
    #Runs the typescript tests.
   