name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Builds the C# code       # Name of step
      run: dotnet build              # Command to run
       
    - name: Runs the C# tests       # Name of step
      run: dotnet test               # Command to run
       
    - name: Builds the typescript code.       # Name of step
      working-directory: ./DotnetTemplate.Web
      run: | 
        npm install              
        npm run build
     
    - name: Runs the linter on the typescript code.       # Name of step
      working-directory: ./DotnetTemplate.Web
      run: npm run lint              # Command to runs-on 
      
    - name: Runs the typescript tests       # Name of step
      working-directory: ./DotnetTemplate.Web
      run: npm t                            # Command to runs-on
      
    
    
    
    
    #Builds the C# code.
    #Runs the C# tests.
    #Builds the typescript code.
    #Runs the linter on the typescript code.
    #Runs the typescript tests.
   