name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: Builds the C# code       # Name of step
      run: dotnet build              # Command to run
      
    
    
    
    
    #Builds the C# code.
    #Runs the C# tests.
    #Builds the typescript code.
    #Runs the linter on the typescript code.
    #Runs the typescript tests.
   